views:
  v1/pods:
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - PF
      - READY
      - RESTARTS
      - STATUS
      - '%CPU/L'
      - '%MEM/L'
      - NODE
  v1/nodes:
    columns:
      - AGE
      - NAME
      - STATUS
      - ROLE
      - VERSION
      - PODS
      - INTERNAL-IP
