#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(find ~/code ~/.config -mindepth 1 -maxdepth 1 -type d | fzy)
    selected=$(tmux-projectgetter | fzy)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# set window title to be selected_name
echo -ne "\033]0;${selected_name}\007"

# Check if the selected item is a file or if the directory contains a single file
if [[ -f $selected ]]; then
    selected_file="$selected"
    selected="$(dirname "$selected")"
else
    file_count=$(find "$selected" -maxdepth 1 -type f | wc -l)
    if [[ $file_count -eq 1 ]]; then
        selected_file=$(find "$selected" -maxdepth 1 -type f)
    else
        selected_file=""
    fi
fi

# new session if not in tmux and tmux is not running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected -d
    if [[ -n $selected_file ]]; then
        tmux send-keys -t $selected_name "nvim '$selected_file'" C-m
    else
        tmux send-keys -t $selected_name "nvim" C-m
    fi
    tmux attach-session -t $selected_name
    exit 0
fi

# new session if not in tmux and tmux is running
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected 
    if [[ -n $selected_file ]]; then
        tmux send-keys -t $selected_name "nvim '$selected_file'" C-m
    else
        tmux send-keys -t $selected_name "nvim" C-m
    fi
fi

# attach to session if in tmux
if [[ -n $TMUX ]]; then
  tmux switch-client -t $selected_name
else
  tmux attach-session -t $selected_name
fi
